version: '3.7'
services:
  nginx:
    image: nginx:alpine
    container_name: nginx-webserver
    ports:
      - "8000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    volumes:
      - ./:/var/www
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql-database
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret

networks:
  app-network:
    driver: bridge
